spring:
  main:
    web-application-type: none
    banner-mode: off
  application:
    name: spring-k8s-hpa
  cloud:
    stream:
      bindings:
        EventConsumer-in-0:
          destination: events.json
          content-type: application/json
          group: ${spring.application.name}
          consumer:
            max-attempts: 1
            concurrency: 5
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
          auto-add-partitions: true
          auto-create-topics: true
        bindings:
          EventConsumer-in-0:
            consumer:
              configuration:
                max.poll.records: 1
                max.poll.interval.ms: 60000 # 1 minute
